### ISSUE TITLE
Changing theme doesn't work

### ISSUE THREAD

**Issue by rash2x** [rash2x/rsou#1]

**Comment by rash2x** [comment]
Надо переписать этот компонент вообще. Чтобы в сервисе брался новый ID темы. Позже опишу логику

**Comment by rash2x** [comment]
![image](https://cloud.githubusercontent.com/assets/3594973/19829405/fe779c92-9de8-11e6-9716-8475fa32d2ef.png)

I submit to page of themes and send request to get list of themes:
**request**:
orgId

**response**:
data: {
themes: []
}
if we have active theme, pass second object: _activeTheme: {}_
if we have private theme, pass third object: _privateThemes: []_

Next we'll merge themes if have similar names on client side.

**Comment by realimbaf** [comment]
server side is ready.

**Comment by rash2x** [comment]
Themes is implemented. 

Please remove ThemeColorID from back-end
![image](https://cloud.githubusercontent.com/assets/3594973/19940626/65dc74b8-a13e-11e6-89d6-32245ffede69.png)
